yarnPath: .yarn/releases/yarn-3.2.4.cjs
nodeLinker: node-modules
npmPublishRegistry: "https://npm.pkg.github.com"
npmScopes:
  thepolicylab-projectportals:
    npmRegistryServer: https://npm.pkg.github.com
