nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.4.1.cjs

npmScopes:
  thepolicylab-projectportals:
    npmRegistryServer: https://npm.pkg.github.com

npmRegistries:
  //npm.pkg.github.com:
    npmAuthToken: ${GITHUB_NPM_REGISTRY_TOKEN}
