nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.4.1.cjs

npmScopes:
  thepolicylab-projectportals:
    npmRegistryServer: https://npm.pkg.github.com
  hollandjg:
    npmRegistryServer: https://npm.pkg.github.com
