backend:
  name: git-gateway
  branch: netlify_cms_data
local_backend: true
publish_mode: editorial_workflow
media_folder: "project-portal-example/content/assets"
public_folder: "/content/assets"
collections:
  - name: projects
    label: Projects
    folder: "project-portal-example/content/projects"
    extension: markdown
    format: frontmatter
    create: true
    fields:
      - { name: path, label: Path, widget: "select", options: ['projects', 'contacts']}
      - { name: question, label: Question, widget: markdown}
      - { name: partnerName, label: Partner Name, widget: "select", options: ["project-portal-satx", "project-portal-nc", "project-portal-example"], required: false}
      - { name: slug, label: Slug }
      - { name: status, label: Status, widget: "select", options: [ "ongoing", "open", "completed" ], required: false}
      - { name: opportunityCloses, label: Opportunity Closes, widget: 'date'}
      - { name: startDate, label: Start Date, required: false, widget: 'date'}
      - { name: endDate, label: End Date, required: false, widget: 'date'}
      - { name: agency, label: Agency, required: false}
      - { name: topics, label: Topics, widget: "select", options: [ "Taxation", "Forms", "Collections", "Government Operations","Human Resources", "Crime and Law Enforcement", "Delinquency Prevention"] }
      - { name: supportNeeded, label: Support Needed, required: false}
      - { name: summary, label: Summary, widget: markdown }
      - { name: deliverable, label: Deliverable, widget: markdown, required: false}
      - { name: purpose, label: Purpose, widget: markdown, required: false}
      - { name: expertise, label: Expertise, widget: markdown, required: false}
      - { name: requirement, label: Requirement, widget: markdown, required: false}
      - { name: keyDates, label: Key Dates, widget: markdown, required: false}
      - { name: statusOfData, label: Status Of Data, required: false}
      - { name: priorResearch, label: Prior Research, required: false}
      - { name: fundingInfo, label: Funding Info, required: false}
      - { name: emailContent, label: Email Content, widget: markdown, required: false}
      - { name: contacts, label: Contacts, widget: "select", options: [ "NC Office of Strategic Partnership", "Duke University", "UNC Chapel Hill", "Kristin Siemek","Volcker Alliance", "Crime and Law Enforcement", "Behavioural Insights Team (BIT)" ] }
      - { name: contactEmail, label: Contact Email, required: false }
      - { name: contactTitle, label: Contact Title, required: false }
      - { name: contactName, label: Contact Name, required: false }
      - { name: lastModified, label: Last Modified, widget: datetime}
  - name: Contacts
    label: Project Contacts
    folder: "project-portal-example/content/contacts"
    create: true
    extension: markdown
    format: frontmatter
    fields:
      - { name: path, label: Path }
      - { name: name, label: Name}
      - { name: title, label: title, required: false }
      - { name: question, label: Question, widget: markdown }
      - { name: partnerName, label: Partner Name, widget: "select", options: [ "North Caroline", "San Antonio", "Example Content" ], required: false }
      - { name: slug, label: Slug, required: false }
      - { name: contactImage, label: Contact Image, widget: "image",required: false}

