# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

permissions:
  contents: read
  packages: write

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@thepolicylab-projectportals'
      - run: yarn install --immutable
      - run: yarn test
      - name: Update version numbers
        run: | 
          yarn workspace "@thepolicylab-projectportals/gatsby-theme-project-portal" version "${{ github.ref_name }}"
          yarn workspace "@thepolicylab-projectportals/project-portal-content-netlify" version "${{ github.ref_name }}"
      - name: Publish packages
        run: | 
          yarn workspace "@thepolicylab-projectportals/gatsby-theme-project-portal" publish
          yarn workspace "@thepolicylab-projectportals/project-portal-content-netlify" publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
