# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@hollandjg'  # replace with scope: '@thepolicylab-projectportals'
          token: ${{ secrets.GITHUB_TOKEN }}
          always-auth: true
      - run: yarn install --immutable
      - run: yarn test
      - name: Update version numbers
        run: | 
          yarn workspace "@hollandjg/gatsby-theme-project-portal" version "${{ github.ref_name }}"
          yarn workspace "@hollandjg/project-portal-content-netlify" version "${{ github.ref_name }}"
      - name: Publish packages
        run: |
          yarn workspace "@hollandjg/gatsby-theme-project-portal" npm publish
          yarn workspace "@hollandjg/project-portal-content-netlify" npm publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
