name: prepare pa11y test on theme

on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    name: Building site and running pa11y-ci tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        site: [example-site]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Enter site directory
        run: cd "packages/${{ matrix.site }}"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

  call-ci-workflow:
    uses: thepolicylab-projectportals/.github/.github/workflows/pa11y-ci.yml@yarn2
    secrets: inherit
    site-name: ${{ matrix.site }}
