name: pa11y tests

on: pull_request

permissions:
  contents: read
  pull-requests: write
  packages: read

jobs:
  call-ci-workflow:
    strategy:
      matrix:
        site: [example-site]
    uses: thepolicylab-projectportals/.github/.github/workflows/pa11y-ci.yml@v5
    secrets: inherit
    with:
      yarn-command: "yarn workspace ${{ matrix.site }}"
      site-name: "${{ matrix.site }}"
