name: pa11y tests

on: pull_request

jobs:
  build:
    name: Building site and running pa11y-ci tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site: [satx]

    env:
      PP_CONFIG_BASE: ${{ format('sites/{0}/', matrix.site) }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - run: npm ci && npm run build
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}

      - name: Start up app
        run: npm run serve & npx wait-on http://localhost:9000

      - name: Run pa11y-ci
        run: npm exec -c 'pa11y-ci -s http://localhost:9000/sitemap/sitemap-index.xml http://localhost:9000 > pa11y_output.html'

      - name: Read pa11y_output file.
        id: pa11y_output
        uses: juliangruber/read-file-action@v1
        with:
          path: ./pa11y_output.html

      - name: Comment on pull request.
        uses: thollander/actions-comment-pull-request@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message:
            "<details><summary><p>Git SHA: <code>${{ github.sha }}</code></p><h3>Pa11y testing results: ${{ matrix.site }} </h3></summary>

            ${{ steps.pa11y_output.outputs.content }}

            </details>"

      - name: Check for pa11y failures.
        if: contains(steps.pa11y_output.outputs.content, 'Error:')
        run: |
          echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the pa11y-ci step in the workflow for details."
          exit 1
